const credentials = [
  {
    country: "DE",
    username: "gutNutzer100",
    email: "somasdslr100@nwytg.net",
    password: "sOMen1(|<2",
    passwordConfirm: "sOMen1(|<2",
    title: "Mr",
    firstName: "Jackie",
    lastName: "Ripper",
    birthYear: "1998", birthMonth: "4", birthDay: "12",
    nationality: "DE",
    countryOfBirth: "DE",
    cityOfBirth: "Berlin",
    streetAndHouse: "red st. 3",
    city: "Berlin",
    postcode: "19291",
    phone: "+18005907441",
    dataProcessing: true
  },
  {
    country: "DE",
    username: "gutNutzer0000002",//this account already registered
    email: "someemail02@nwytg.net",
    password: "sOMen1(|<2",
    passwordConfirm: "sOMen1(|<2",
    title: "Mr",
    firstName: "Daniels",
    lastName: "Jack",
    birthYear: "1998", birthMonth: "4", birthDay: "12",
    nationality: "NL",
    countryOfBirth: "TR",
    cityOfBirth: "Ankara",
    streetAndHouse: "red st. 3",
    city: "Ankara",
    postcode: "19093",
    phone: "+18005947242",
    dataProcessing: true
  },
  {
    country: "DE",
    username: "gutNutzer0033",
    email: "someemail0033@nwytg.net",
    password: "sOMen1(|<2",
    passwordConfirm: "sOMen1(|<2",
    title: "Mr",
    firstName: "Flow",
    lastName: "Moses",
    birthYear: "1998", birthMonth: "4", birthDay: "12",
    nationality: "GB",
    countryOfBirth: "TR",
    cityOfBirth: "Ankara",
    streetAndHouse: "red st. 3",
    city: "Ankara",
    postcode: "19023",
    phone: "+18005947493",
    dataProcessing: true
  },
];
const credentialsSelectors = {
  country: '#registerForm\\:country',
  username: '#registerForm\\:login',
  email: '#registerForm\\:email',
  password: '#registerForm\\:password',
  passwordConfirm: "#registerForm\\:passwordConfirm",
  title: {"Mr": '#registerForm\\:salutation\\:0', "Ms/Mrs": '#registerForm\\:salutation\\:1'},
  firstName: "#registerForm\\:firstName",
  lastName: "#registerForm\\:lastName",
  birthYear: "#registerForm\\:year", birthMonth: "#registerForm\\:month", birthDay: "#registerForm\\:day",
  nationality: "#registerForm\\:nationality",
  countryOfBirth: "#registerForm\\:birthCountry",
  cityOfBirth: "#registerForm\\:birthCity",
  streetAndHouse: "#registerForm\\:street",
  city: "#registerForm\\:city",
  postcode: "#registerForm\\:zipCode",
  phone: "#registerForm\\:phoneMobile",
  dataProcessing: "#registerForm\\:dataProcessing"
};
const submitSelector = "#registerForm\\:registerButtonGDPR";
module.exports = {credentials, credentialsSelectors, submitSelector};